- name: Install Bing Wallpaper extensions
  ansible.builtin.include_tasks: helpers/enable-extension.yml
  vars:
    extension: bingwallpaper@ineffable-gmail.com

- name: Ensure download folder exists 
  ansible.builtin.file:
    path: "{{ user.home }}/Vault/Archive/Wallpapers/Bing Wallpaper"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "u=rwx,g=rx"
  become: true

- name: Set download folder
  community.general.dconf:
    key: "/org/gnome/shell/extensions/bingwallpaper/download-folder"
    value: "'{{ user.home }}/Vault/Archive/Wallpapers/Bing Wallpaper'" 
    state: present
  become: true
  become_user: "{{ user.name }}"

- name: Set market
  community.general.dconf:
    key: "/org/gnome/shell/extensions/bingwallpaper/market"
    value: "'pt-BR'" 
    state: present
  become: true
  become_user: "{{ user.name }}"

- name: Set resolution
  community.general.dconf:
    key: "/org/gnome/shell/extensions/bingwallpaper/resolution"
    value: "'UHD'"
    state: present
  become: true
  become_user: "{{ user.name }}"

