- name: Ensure git directory exists
  ansible.builtin.file:
    path: "{{ user.home }}/.config/git"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"
  become: true

- name: Generate git Config
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "{{ user.home }}/.config/git/config"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
  become: true
