- name: Import 1Password secrets tasks
  ansible.builtin.import_tasks:
    file: onepassword.yml
  tags:
    - secrets-onepassword

- name: Import Git secrets tasks
  ansible.builtin.import_tasks:
    file: git.yml
  tags:
    - secrets-git
