- name: Verify if has an 1Password account
  ansible.builtin.command: "op account list"
  register: onepassword_account_list
  changed_when: false

- name: Get 1Password master password
  ansible.builtin.pause:
    prompt: Enter 1Password master password
  register: onepassword_master_password

- name: Get 1Password credentials
  when: onepassword_account_list.stdout == ""
  block:
    - name: Get 1Password Subdomain
      ansible.builtin.pause:
        prompt: Enter 1Password subdomain
      register: onepassword_subdomain

    - name: Get 1Password email
      ansible.builtin.pause:
        prompt: Enter 1Password email
      register: onepassword_email

    - name: Get 1Password secret key
      ansible.builtin.pause:
        prompt: Enter 1Password secret key
      register: onepassword_secret_key

    - name: Add 1Password account
      no_log: false
      ansible.builtin.debug:
        msg: "Adding 1Password account. Test: {{ onepassword_login_test }}"
      vars:
        onepassword_login_test: "{{ lookup('community.general.onepassword',
          'PC User',
          field='username',
          subdomain=onepassword_subdomain.user_input,
          master_password=onepassword_master_password.user_input,
          username=onepassword_email.user_input,
          secret_key=onepassword_secret_key.user_input) }}"
