- name: Fedora setup
  hosts: all

  vars_files:
    - user.yml

  roles:
    - role: fedora
      tags:
        - system
      when: "ansible_facts.distribution == 'Fedora'"

    - role: user
      tags:
        - user

    - role: secrets
      tags:
        - secrets
