- name: Copy dotfiles
  ansible.builtin.copy:
    src: dotfiles/ 
    dest: "{{ user.home }}/"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: preserve

- name: Clone Neovim kickstart
  ansible.builtin.git:
    repo: "https://github.com/nvim-lua/kickstart.nvim.git"
    dest: "{{ user.home }}/.config/nvim"
    single_branch: true
    version: master
    clone: true
