- name: Install system packages
  ansible.builtin.dnf:
    name:
      - "@base-x"
      - "@hardware-support"
      - "@networkmanager-submodules"
      - "@multimedia"
      - lightdm-gtk
      - i3
      - cargo
      - dunst
      - rofi
      - lxpolkit
      - xrandr
      - autorandr
      - xset
      - picom
      - xdg-user-dirs
      - gnome-keyring
      - adwaita-cursor-theme
      - adwaita-gtk2-theme
      - adwaita-icon-theme
      - feh
      - alacritty
      - mpv
      - transmission
      - fish
    state: present
    exclude:
      - rxvt-unicode
      - xss-lock
      - dmenu
    update_cache: true
  become: true

- name: Enable LightDM service
  ansible.builtin.systemd:
    name: lightdm
    enabled: true
  become: true

- name: Show sudo password feedback
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: "^Defaults env_reset"
    line: "Defaults env_reset,pwfeedback"
    state: present
  become: true
