- name: Install system packages
  ansible.builtin.dnf:
    name:
      - "@base-x"
      - "@hardware-support"
      - lightdm-gtk
      - i3
      - dunst
      - rofi
      - lxpolkit
      - xrandr
      - autorandr
      - xset
      - picom
      - xdg-desktop-portal
      - xdg-desktop-portal-gtk
      - xdg-user-dirs
      - gnome-keyring
      - adwaita-cursor-theme
      - adwaita-gtk2-theme
      - adwaita-icon-theme
      - adwaita-qt5
      - adwaita-qt6
      - libadwaita
      - libadwaita-qt5
      - libadwaita-qt6
      - flatpak
      - feh
      - alacritty
    state: present
    exclude:
      - rxvt-unicode
      - xss-lock
      - dmenu
    update_cache: true
  become: true

- name: Enable LightDM service
  ansible.builtin.systemd:
    name: lightdm
    enabled: true
  become: true
