- name: Add Flathub repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
  become: true

- name: Install Flatpak packages
  community.general.flatpak:
    name:
      - org.qbittorrent.qBittorrent
      - org.videolan.VLC
    state: present
  become: true

- name: Remove Flatpak packages
  community.general.flatpak:
    name:
      - org.mozilla.firefox
      - com.google.Chrome
    state: absent
  become: true
