- name: Ensure Flathub is enabled
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"

- name: Install Flatpak packages
  community.general.flatpak:
    name:
      - com.spotify.Client
      - ca.desrt.dconf-editor
      - org.qbittorrent.qBittorrent
      - io.httpie.Httpie
    state: present

- name: Remove Flatpak packages
  community.general.flatpak:
    name:
      - com.usebruno.Bruno
      - de.haeckerfelix.Fragments
    state: absent


