- name: Ensure Flathub is enabled
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
  become: true

- name: Install Flatpak packages
  community.general.flatpak:
    name:
      - com.spotify.Client
    state: present
  become: true
