- name: Install Gnome extensions manager
  ansible.builtin.dnf:
    name:
      - gnome-extensions-app
    state: present
  become: true

- name: Install Gnome extensions
  ansible.builtin.include_role:
    name: common
    tasks_from: enable-gnome-extension
  vars:
    extension_id: "{{ item }}"
  loop: 
    - appindicatorsupport@rgcjonas.gmail.com
    - launch-new-instance@gnome-shell-extensions.gcampax.github.com

