- ansible.builtin.import_tasks: dependencies/main.yml
- ansible.builtin.import_tasks: repositories/main.yml
- ansible.builtin.import_tasks: system/main.yml
- ansible.builtin.import_tasks: user/main.yml
- ansible.builtin.import_tasks: gnome/main.yml
- ansible.builtin.import_tasks: software/main.yml
