- name: Update system packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true
  become: true

- name: Install various packages
  ansible.builtin.dnf:
    name: 
      - mpv
    state: present
  become: true
