- name: Ensure Vault folder exists
  ansible.builtin.file:
    path: "{{ user.home }}/Vault"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Create Vault folders
  ansible.builtin.file:
    path: "{{ user.home }}/Vault/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"
  with_items:
      - Archive
      - Backups
      - Documents
      - Projects
      - Media
      - Resources
  become: true

- name: Create Vault media folders
  ansible.builtin.file:
    path: "{{ user.home }}/Vault/Media/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"
  with_items:
      - Anime
      - Books
      - Games
      - Movies
      - Music
      - Series
  become: true

- name: Ensure gtk3 config folder exists
  ansible.builtin.file:
    path: "{{ user.home }}/.config/gtk-3.0"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "u=rwx,g=rx,o=rx"
  become: true

- name: Template vault bookmarks
  ansible.builtin.template:
    src: vault/bookmarks.j2
    dest: "{{ user.home }}/.config/gtk-3.0/bookmarks"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "u=rw,g=r,o=r"
  become: true
