backend = "glx";
glx-no-stencil = true;
glx-no-rebing-pixmap = true;
# xrender-sync-fence = true;

vsync = true;
no-frame-pacing = true;

corner-radius = 6;

rounded-corners-exclude = [
	"window_type = 'dock'",
];

shadow = true;
shadow-radius = 56;
shadow-opacity = 0.5;
shadow-offset-x = -56;
shadow-offset-y = -36;

crop-shadow-to-monitor = true;

shadow-exclude = [
	"_NET_WM_WINDOW_TYPE@:a = '_NET_WM_WINDOW_TYPE_NORMAL' && ! I3_FLOATING_WINDOW@:c",
	"class_g = 'i3-frame'",
];

fading = false;

transparent-clipping = false;

opacity-rule = [
	"0:_NET_WM_STATE@[*]:32a *= '_NET_WM_STATE_HIDDEN'",
];

blur: {
  method = "dual_kawase";
  strength = 8;
  background = false;
  background-frame = false;
  background-fixed = true;
};

dithered-present = true;

wintypes: {
	menu: {
		shadow: false;
		blur-background: false;
	};
	dock: {
		shadow: false;
		clip-shadow-above: true;
		blur-background: true;
	};
};

