- name: Add Docker repo
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  become: true

- name: Install Docker packages
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - docker-buildx-plugin
    state: present
    update_cache: true
  become: true

- name: Append user to docker group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: "docker"
    append: true
  become: true
