- name: Ensure Flathub is enabled
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
  become: true
  become_user: "{{ user.name }}"

- name: Install Flatpak packages
  community.general.flatpak:
    name:
      - com.spotify.Client
      - ca.desrt.dconf-editor
      - org.qbittorrent.qBittorrent
      - org.videolan.VLC
      - com.github.xournalpp.xournalpp
      - com.obsproject.Studio
    state: present
  become: true
  become_user: "{{ user.name }}"

- name: Remove Flatpak packages
  community.general.flatpak:
    name:
      - com.usebruno.Bruno
      - de.haeckerfelix.Fragments
      - io.httpie.Httpie
      - com.github.johnfactotum.Foliate
    state: absent
  become: true
  become_user: "{{ user.name }}"


