- name: Get release info
  ansible.builtin.uri:
    url: "https://data.services.jetbrains.com/products/releases?code=TBA&latest=true&type=release"
    return_content: true
  register: r_jetbrains_toolbox_info

- name: Create temporary directory
  ansible.builtin.file:
    path: /tmp/jetbrains_toolbox
    state: directory

- name: Download JetBrains Toolbox file
  ansible.builtin.get_url:
    url: "{{ r_jetbrains_toolbox_info.json.TBA[0].downloads.linux.link }}"
    dest: /tmp/jetbrains_toolbox/jetbrains_toolbox.tar.gz
    checksum: "sha256:{{ r_jetbrains_toolbox_info.json.TBA[0].downloads.linux.checksumLink }}"

- name: Extract AppImage
  ansible.builtin.unarchive:
    src: /tmp/jetbrains_toolbox/jetbrains_toolbox.tar.gz
    dest: /tmp/jetbrains_toolbox
    remote_src: true
    list_files: true

- name: Run JetBrains Toolbox
  ansible.builtin.shell: "/tmp/jetbrains_toolbox/{{r_jetbrains_toolbox_files.files[1]}}"
  become: true
  become_user: "{{ user.name }}"

- name: Delete temporary directory
  ansible.builtin.file:
    path: /tmp/jetbrains_toolbox
    state: absent
