- name: Install Nvidia driver and graphics packages
  ansible.builtin.dnf:
    name:
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda
      - xorg-x11-drv-nvidia-cuda-libs
      - nvidia-vaapi-driver
      - libva-utils
      - vulkan
    state: present
  become: true

- name: Add Kernel parameters for Nvidia driver
  ansible.builtin.command: 'grubby --args="{{ item }}" --update-kernel=ALL'
  loop:
    - "nvidia.NVreg_RegistryDwords=EnableBrightnessControl=1"
  become: true

- name: Use Nvidia open kernel modules
  ansible.builtin.command: |
    sh -c 'echo "%_with_kmod_nvidia_open 1" > /etc/rpm/macros.nvidia-kmod'
  become: true

- name: Rebuild akmods
  ansible.builtin.command: akmods --kernels $(uname -r) --rebuild
  become: true
