- name: Install Nvidia driver and graphics packages
  ansible.builtin.dnf:
    name:
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda
      - xorg-x11-drv-nvidia-cuda-libs
      - nvidia-vaapi-driver
      - libva-utils
      - vulkan
    state: present
  become: true
  
- name: Copy Nvidia driver configuration file
  ansible.builtin.copy:
    src: nvidia/nvidia.conf
    dest: "/etc/modprobe.d/"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
    directory_mode: "u=rwx,g=rx,o=rx"
  become: true
