- name: Set dnf max parallel downloads
  community.general.ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: max_parallel_downloads
    value: 20
    no_extra_spaces: true
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
    state: present
  become: true
