- name: Install gnome-extensions-cli
  ansible.builtin.pip:
    name: gnome-extensions-cli
    extra_args: --upgrade
    executable: pip3

- name: Install Gnome extension
  ansible.builtin.command: gext install --filesystem {{ extension_id }}
  register: r_gext

