- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto
  become: true

- name: Install Deskplay dependencies
  ansible.builtin.dnf:
    name:
      - python3-psutil
      - python3-pip
    state: present
  become: true
